# OaMatrix

OaMatrix contains the eigensolvers used in Oasys, as well as several useful tools for numerical linear algebra.

OaMatrix contains the eigensolvers
- Gep11
- Sep11

Gep11 solves the generalised eigenvalue problem
$$Kx=\lambda Mx$$
and Sep11 solves the standard eigenvalue problem
$$Kx=\lambda x$$

Some of the tools OaMatrix contains are
- OaPardiso - Solves the [LLT or LDLT decomposition of a matrix](https://en.wikipedia.org/wiki/Cholesky_decomposition).
- SymmetricEigenCounter - Counts the number of eigenvalues in an interval for an eigenvalue problem using [Sylvester's Law of Inertia](https://en.wikipedia.org/wiki/Sylvester%27s_law_of_inertia).

## Gep11 Principles

Gep11 uses subspace iteration with shifting and locking. The core aspect of subspace iteration works as follows.


In [2]:
import sys
!{sys.executable} -m pip install numpy

In [12]:
import numpy as np
matrixSize = 10 
A = np.random.rand(matrixSize, matrixSize)
M = np.dot(A, A.transpose())
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print(M)

[[ 1.730  1.735  2.682  2.490  1.584  1.215  2.288  1.804  1.950  1.832]
 [ 1.735  3.322  3.148  3.304  1.993  2.097  2.726  2.594  3.035  3.034]
 [ 2.682  3.148  6.145  4.137  2.843  2.668  4.659  3.920  4.315  3.306]
 [ 2.490  3.304  4.137  4.727  2.284  2.619  3.518  3.413  3.633  3.306]
 [ 1.584  1.993  2.843  2.284  2.030  1.307  2.410  2.066  2.483  2.190]
 [ 1.215  2.097  2.668  2.619  1.307  1.828  2.127  2.309  2.391  1.863]
 [ 2.288  2.726  4.659  3.518  2.410  2.127  4.229  3.076  3.389  2.670]
 [ 1.804  2.594  3.920  3.413  2.066  2.309  3.076  3.373  3.319  2.596]
 [ 1.950  3.035  4.315  3.633  2.483  2.391  3.389  3.319  4.223  3.064]
 [ 1.832  3.034  3.306  3.306  2.190  1.863  2.670  2.596  3.064  3.428]]
